### ISSUE TITLE
0e0 not parsed

### ISSUE THREAD

**Issue by eleumik** [coconut2015/cookjson#2]
Hi,

while testing some json parsers I found that cookjson fails in parsing the following numbers, that are valid json numbers: `0e0`  `-0` 

I also observed that the numbers `-0.0` and `-0.0E0` are parsed without errors, however they are bound to a BigDecimal that cannot represent a negative zero, only a Double or a Float could, but probably this is not a real issue. 

Bye
Michele

**Comment by coconut2015** [comment]
I looked at the JSON spec again, and it looked that I may have understood the graph a bit incorrectly regarding 0e0 (i.e. I thought only . could follow 0).  I looked at several online JSON validators and they seem to allow 0e0.

As for -0.0, -0.0E0, I think that it is fine as 0 (and represented as 0 in BigDecimal).  I don't think that is an issuel.  As for double / float having negative 0, that has more to do with the quirkiness of the internal format than the actual intention.

**Comment by eleumik** [comment]
I can confirm that most implementations I checked support `0e0` and `-0`

I agree that the minus zero thing is something not very relevant,  a thing I can think of is a Jsonschema implementation that uses `type` `integer` and wants to reject `-0` or in general an application that wants to tell clients that is not possible to send `-0`

If you are interested, I found these on the argument:

https://github.com/json-schema/json-schema/issues/27
https://www.ietf.org/mail-archive/web/json/current/msg03668.html
https://www.ietf.org/mail-archive/web/json/current/msg01661.html

**Comment by coconut2015** [comment]
#3
